TITLE FAZER UM PROGRAMA QUE DECODIFIQUE UMA MENSAGEM CIFRADA (CONSIDERAR SÓ CARACTERES MAIUSCULOS)

.MODEL SMALL

.STACK 100

.DATA
ORIGEM DB A, B, C ,D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z
CODIFICADO DB Q, W, E, R, T, Y, U, I, O, P, A, S, D, F, G, H, J, K, L, Z, X, C, V, B, N, M
M DB ?
C DB ?
D DB ?

.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX

    CALL LER

    CALL CODIFICA

    CALL DECODIFICA

MOV AH, 4CH
INT 21h
MAIN ENDP



END MAIN